// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlolhcrygcthnhpwrhcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsb2xoY3J5Z2N0aG5ocHdyaGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjI0NjgsImV4cCI6MjA1Nzc5ODQ2OH0.0AkZS8CGY9CLJ_Wp3ysUfP-y6-KmT00m1DI980Pv1og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);